@hostname = http://localhost:5000/api/v1

### Test connection
GET {{hostname}}

### Register Seeder
POST {{hostname}}/auth/register
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456",
    "username" : "test"
}

### Login
POST {{hostname}}/auth/login?device=android
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"
}

### Logout
DELETE {{hostname}}/auth/logout

### otp
POST {{hostname}}/auth/otp
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZmVlNThmLTY3OTgtNDBjNi1hZjYwLWFlZTk2Y2QxNzEwOSIsImlhdCI6MTcwNTM4MTc3NCwiZXhwIjoxNzA1NDY4MTc0fQ.sTRpV2YMsqE5ZTkEnfJB22NUz1PUiEsdfFfqhob6pYM",
    "otp": "745682",
    "device": "android"
}

### resend otp
GET {{hostname}}/auth/resendotp?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZmVlNThmLTY3OTgtNDBjNi1hZjYwLWFlZTk2Y2QxNzEwOSIsImlhdCI6MTcwNTM4MTc3NCwiZXhwIjoxNzA1NDY4MTc0fQ.sTRpV2YMsqE5ZTkEnfJB22NUz1PUiEsdfFfqhob6pYM


### test auth
GET {{hostname}}/test_auth